"""
Test suite for Executive Summary Service.

Components:
- Auto-generated executive summary
- Key takeaways extraction
- Action item suggestions
"""

import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'backend'))


class TestExecutiveSummaryServiceExists:
    @pytest.fixture
    def service_file_content(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        with open(service_file, 'r') as f:
            return f.read()

    def test_service_file_exists(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        assert os.path.exists(service_file)

    def test_service_class_exists(self, service_file_content):
        assert 'class ExecutiveSummaryService' in service_file_content


class TestAutoGeneratedSummary:
    @pytest.fixture
    def service_file_content(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        with open(service_file, 'r') as f:
            return f.read()

    def test_has_generate_executive_summary_method(self, service_file_content):
        assert 'def generate_executive_summary(' in service_file_content

    def test_has_create_summary_sections_method(self, service_file_content):
        assert 'def create_summary_sections(' in service_file_content


class TestKeyTakeaways:
    @pytest.fixture
    def service_file_content(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        with open(service_file, 'r') as f:
            return f.read()

    def test_has_extract_key_takeaways_method(self, service_file_content):
        assert 'def extract_key_takeaways(' in service_file_content

    def test_has_prioritize_takeaways_method(self, service_file_content):
        assert 'def prioritize_takeaways(' in service_file_content


class TestActionItems:
    @pytest.fixture
    def service_file_content(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        with open(service_file, 'r') as f:
            return f.read()

    def test_has_suggest_action_items_method(self, service_file_content):
        assert 'def suggest_action_items(' in service_file_content

    def test_has_assign_priorities_method(self, service_file_content):
        assert 'def assign_priorities(' in service_file_content

    def test_has_generate_recommendations_method(self, service_file_content):
        assert 'def generate_recommendations(' in service_file_content


class TestConfiguration:
    @pytest.fixture
    def service_file_content(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        with open(service_file, 'r') as f:
            return f.read()

    def test_has_get_summary_config_method(self, service_file_content):
        assert 'def get_summary_config(' in service_file_content


class TestTypeHints:
    @pytest.fixture
    def service_file_content(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        with open(service_file, 'r') as f:
            return f.read()

    def test_imports_typing_modules(self, service_file_content):
        assert 'from typing import' in service_file_content

    def test_uses_dict_type_hint(self, service_file_content):
        assert 'Dict[' in service_file_content

    def test_uses_list_type_hint(self, service_file_content):
        assert 'List[' in service_file_content


class TestDocstrings:
    @pytest.fixture
    def service_file_content(self):
        service_file = os.path.join(
            os.path.dirname(__file__),
            '..', 'backend', 'services', 'executive_summary_service.py'
        )
        with open(service_file, 'r') as f:
            return f.read()

    def test_module_docstring_exists(self, service_file_content):
        assert service_file_content.strip().startswith('"""')

    def test_class_docstring_exists(self, service_file_content):
        if 'class ExecutiveSummaryService' in service_file_content:
            idx = service_file_content.find('class ExecutiveSummaryService')
            class_section = service_file_content[idx:idx+500]
            assert '"""' in class_section
