/**
 * Knowledge Base Page
 *
 * Phase 3: Complete revamp with pattern group integration.
 * - Tabs for different article categories
 * - Source type filtering (manual, auto-generated)
 * - Pattern-linked article badges
 * - Modern design matching Edge Cases page
 */

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  RefreshCw,
  Plus,
  BookOpen,
  FileText,
  Lightbulb,
  Wrench,
  Eye,
  Link2,
  Sparkles,
} from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import { getKnowledgeBaseArticles } from '../../services/knowledgeBase.service';
import type {
  KnowledgeBaseArticle,
  KnowledgeBaseListParams,
} from '../../types/knowledgeBase';
import { SOURCE_TYPE_LABELS, SOURCE_TYPE_COLORS } from '../../types/knowledgeBase';
import { SearchInput, Dropdown } from '../../components/common';
import type { DropdownOption } from '../../components/common';

type TabType = 'all' | 'pattern-insights' | 'guides' | 'troubleshooting';

const TABS: { id: TabType; label: string; icon: React.ReactNode; category?: string }[] = [
  { id: 'all', label: 'All Articles', icon: <BookOpen size={16} /> },
  { id: 'pattern-insights', label: 'Pattern Insights', icon: <Sparkles size={16} />, category: 'pattern-insights' },
  { id: 'guides', label: 'Guides', icon: <Lightbulb size={16} />, category: 'guides' },
  { id: 'troubleshooting', label: 'Troubleshooting', icon: <Wrench size={16} />, category: 'troubleshooting' },
];

const SOURCE_TYPE_OPTIONS: DropdownOption[] = [
  { value: '', label: 'All Sources' },
  { value: 'manual', label: 'Manual' },
  { value: 'auto_generated', label: 'Auto-Generated' },
  { value: 'pattern_derived', label: 'Pattern Derived' },
];

const buildExcerpt = (content: string, maxLength = 180): string => {
  const plainText = content
    .replace(/[#_*`>\\-]/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  if (plainText.length <= maxLength) {
    return plainText;
  }

  return `${plainText.slice(0, maxLength - 3)}...`;
};

const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
};

const KnowledgeBase: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();

  // State
  const [articles, setArticles] = useState<KnowledgeBaseArticle[]>([]);
  const [allArticles, setAllArticles] = useState<KnowledgeBaseArticle[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [sourceFilter, setSourceFilter] = useState('');

  // Tab state from URL
  const activeTab = (searchParams.get('tab') as TabType) || 'all';

  const setActiveTab = (tab: TabType) => {
    setSearchParams({ tab });
  };

  // Fetch articles
  const fetchArticles = useCallback(
    async (params?: Partial<KnowledgeBaseListParams>) => {
      setLoading(true);
      setError(null);

      try {
        const tab = TABS.find((t) => t.id === activeTab);
        const queryParams: KnowledgeBaseListParams = {
          ...params,
          limit: 50,
        };

        // Apply category filter based on tab
        if (tab?.category) {
          queryParams.category = tab.category;
        }

        // Apply source type filter
        if (sourceFilter) {
          queryParams.sourceType = sourceFilter as KnowledgeBaseListParams['sourceType'];
        }

        const response = await getKnowledgeBaseArticles(queryParams);
        setArticles(response.items);

        // Also fetch all articles for stats if on a filtered tab
        if (tab?.category || sourceFilter) {
          const allResponse = await getKnowledgeBaseArticles({ limit: 100 });
          setAllArticles(allResponse.items);
        } else {
          setAllArticles(response.items);
        }
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : 'Failed to load articles';
        setError(message);
        setArticles([]);
      } finally {
        setLoading(false);
      }
    },
    [activeTab, sourceFilter]
  );

  useEffect(() => {
    fetchArticles();
  }, [fetchArticles]);

  const handleSearchSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const trimmed = searchTerm.trim();
    await fetchArticles({ search: trimmed || undefined });
  };

  const handleRefresh = () => {
    fetchArticles();
  };

  // Stats from all articles
  const stats = useMemo(() => {
    const total = allArticles.length;
    const patternLinked = allArticles.filter((a) => a.patternGroupId).length;
    const autoGenerated = allArticles.filter((a) => a.sourceType === 'auto_generated').length;
    const published = allArticles.filter((a) => a.isPublished).length;

    return { total, patternLinked, autoGenerated, published };
  }, [allArticles]);

  // Tab counts from all articles
  const tabCounts = useMemo(() => {
    const counts: Record<TabType, number> = {
      all: allArticles.length,
      'pattern-insights': allArticles.filter((a) => a.category === 'pattern-insights').length,
      guides: allArticles.filter((a) => a.category === 'guides').length,
      troubleshooting: allArticles.filter((a) => a.category === 'troubleshooting').length,
    };
    return counts;
  }, [allArticles]);

  return (
    <>
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-[var(--color-content-primary)] flex items-center gap-3">
            <BookOpen className="w-6 h-6" style={{ color: '#2A6B6E' }} />
            Knowledge Base
          </h1>
          <p className="text-sm text-[var(--color-content-muted)] mt-1">
            Documentation, guides, and pattern-generated insights
          </p>
        </div>
        <div className="flex gap-3 items-center">
          <button
            className="px-4 py-2.5 rounded-lg text-sm font-semibold transition-all inline-flex items-center gap-2 text-white hover:shadow-lg hover:-translate-y-0.5"
            style={{ background: 'linear-gradient(135deg, #2A6B6E 0%, #11484D 100%)' }}
            onClick={() => navigate('/knowledge-base/new')}
          >
            <Plus size={14} /> New Article
          </button>
          <button
            className="p-2.5 rounded-lg text-sm font-semibold transition-all inline-flex items-center gap-2 bg-[var(--color-surface-inset)] text-[var(--color-content-secondary)] border border-[var(--color-border-default)] hover:bg-[var(--color-interactive-active)]"
            onClick={handleRefresh}
          >
            <RefreshCw size={18} />
          </button>
        </div>
      </div>

      {/* Stats Bar */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div className="bg-[var(--color-surface-raised)] rounded-lg p-3 text-center border border-[var(--color-border-default)]">
          <div className="text-2xl font-bold text-[var(--color-content-primary)]">
            {stats.total}
          </div>
          <div className="text-xs text-[var(--color-content-muted)]">Total Articles</div>
        </div>
        <div className="bg-[var(--color-surface-raised)] rounded-lg p-3 text-center border border-[var(--color-status-purple)]">
          <div className="text-2xl font-bold text-[var(--color-status-purple)]">
            {stats.patternLinked}
          </div>
          <div className="text-xs text-[var(--color-status-purple)]">Pattern-Linked</div>
        </div>
        <div className="bg-[var(--color-surface-raised)] rounded-lg p-3 text-center border border-[var(--color-status-info)]">
          <div className="text-2xl font-bold text-[var(--color-status-info)]">
            {stats.autoGenerated}
          </div>
          <div className="text-xs text-[var(--color-status-info)]">Auto-Generated</div>
        </div>
        <div className="bg-[var(--color-surface-raised)] rounded-lg p-3 text-center border border-[var(--color-status-success)]">
          <div className="text-2xl font-bold text-[var(--color-status-success)]">
            {stats.published}
          </div>
          <div className="text-xs text-[var(--color-status-success)]">Published</div>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-[var(--color-surface-raised)] rounded-xl shadow-sm border border-[var(--color-border-default)] mb-6">
        <div className="px-6 border-b border-[var(--color-border-default)]">
          <nav className="-mb-px flex space-x-8 overflow-x-auto">
            {TABS.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`py-3 px-1 border-b-2 font-medium text-sm flex items-center gap-2 transition-colors whitespace-nowrap ${
                  activeTab === tab.id
                    ? 'border-primary text-primary'
                    : 'border-transparent text-[var(--color-content-muted)] hover:text-[var(--color-content-secondary)] hover:border-[var(--color-border-default)]'
                }`}
              >
                {tab.icon}
                {tab.label}
                <span className="ml-1 px-2 py-0.5 text-xs rounded-full bg-[var(--color-surface-inset)] text-[var(--color-content-secondary)]">
                  {tabCounts[tab.id]}
                </span>
              </button>
            ))}
          </nav>
        </div>
      </div>

      {/* Search and Filters */}
      <div className="bg-[var(--color-surface-raised)] p-4 rounded-xl mb-5 shadow-sm">
        <div className="flex flex-col sm:flex-row gap-3 sm:items-center">
          <form onSubmit={handleSearchSubmit}>
            <SearchInput
              id="kb-search"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search articles..."
            />
          </form>

          {/* Source Type Filter */}
          <Dropdown
            value={sourceFilter}
            onChange={setSourceFilter}
            options={SOURCE_TYPE_OPTIONS}
            placeholder="All Sources"
          />
        </div>
      </div>

      {/* Content */}
      {loading ? (
        <div className="bg-[var(--color-surface-raised)] rounded-xl p-6 shadow-sm">
          <div className="flex flex-col items-center justify-center p-20">
            <div
              className="w-12 h-12 border-4 border-[var(--color-border-default)] rounded-full animate-spin mb-4"
              style={{ borderTopColor: '#2A6B6E' }}
            />
            <div className="text-lg font-semibold text-[var(--color-content-primary)] mb-2">
              Loading Articles...
            </div>
          </div>
        </div>
      ) : error ? (
        <div className="p-4 rounded-lg mb-5 flex items-center gap-3 bg-[var(--color-status-danger-bg)] text-[var(--color-status-danger)] border-l-4 border-[var(--color-status-danger)]">
          <FileText size={20} />
          <div className="flex-1">
            <div className="font-semibold">Unable to load articles</div>
            <div className="text-sm mt-1">{error}</div>
          </div>
        </div>
      ) : articles.length === 0 ? (
        <div className="bg-[var(--color-surface-raised)] rounded-xl p-6 shadow-sm">
          <div className="flex flex-col items-center justify-center p-20">
            <div className="text-6xl mb-4">
              <BookOpen size={64} className="text-[var(--color-content-muted)]" />
            </div>
            <div className="text-lg font-semibold text-[var(--color-content-primary)] mb-2">
              No Articles Found
            </div>
            <div className="text-sm text-[var(--color-content-muted)]">
              {searchTerm
                ? 'Try adjusting your search criteria.'
                : 'Create your first article to get started.'}
            </div>
          </div>
        </div>
      ) : (
        <div className="grid gap-6 grid-cols-1 md:grid-cols-2">
          {articles.map((article) => (
            <div
              key={article.id}
              className="bg-[var(--color-surface-raised)] rounded-xl p-6 shadow-sm hover:shadow-lg hover:-translate-y-0.5 transition-all cursor-pointer flex flex-col gap-4"
              onClick={() => navigate(`/knowledge-base/${article.id}`)}
            >
              {/* Header Row */}
              <div className="flex justify-between items-start gap-4">
                <h2 className="text-lg font-semibold text-[var(--color-content-primary)] line-clamp-2">
                  {article.title}
                </h2>
                <div className="flex flex-col gap-1 items-end shrink-0">
                  {/* Source Type Badge */}
                  <span
                    className={`px-2.5 py-1 rounded-md text-xs font-semibold ${
                      SOURCE_TYPE_COLORS[article.sourceType] || 'bg-[var(--color-surface-inset)] text-[var(--color-content-primary)]'
                    }`}
                  >
                    {SOURCE_TYPE_LABELS[article.sourceType] || article.sourceType}
                  </span>
                  {/* Category Badge */}
                  {article.category && (
                    <span className="px-2 py-0.5 rounded text-xs bg-[var(--color-surface-inset)] text-[var(--color-content-secondary)] capitalize">
                      {article.category.replace(/-/g, ' ')}
                    </span>
                  )}
                </div>
              </div>

              {/* Excerpt */}
              <p className="text-sm text-[var(--color-content-secondary)]">
                {buildExcerpt(article.content)}
              </p>

              {/* Pattern Link Badge */}
              {article.patternGroupId && (
                <div className="flex items-center gap-2 text-[var(--color-status-purple)]">
                  <Link2 size={14} />
                  <span className="text-xs font-medium">Linked to Pattern Group</span>
                </div>
              )}

              {/* Tags */}
              {article.tags && article.tags.length > 0 && (
                <div className="flex gap-2 flex-wrap">
                  {article.tags.slice(0, 4).map((tag) => (
                    <span
                      key={tag}
                      className="px-2 py-1 bg-[var(--color-surface-inset)] rounded-md text-xs text-[var(--color-content-secondary)]"
                    >
                      {tag}
                    </span>
                  ))}
                  {article.tags.length > 4 && (
                    <span className="px-2 py-1 text-xs text-[var(--color-content-muted)]">
                      +{article.tags.length - 4} more
                    </span>
                  )}
                </div>
              )}

              {/* Footer */}
              <div className="flex justify-between items-center mt-auto pt-2 border-t border-[var(--color-border-subtle)]">
                <span className="text-xs text-[var(--color-content-muted)]">
                  Updated {formatDate(article.updatedAt)}
                </span>
                <div className="flex items-center gap-1 text-xs text-[var(--color-content-muted)]">
                  <Eye size={12} />
                  {article.views} views
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </>
  );
};

export default KnowledgeBase;
