"""
Activity feed API endpoints (TASK-363).

Provides read-only access to recent activity log entries with optional
filters for user, action type, resource type, and time window.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from api.database import get_db
from api.dependencies import get_current_user_with_db
from api.schemas.activity import ActivityFeedPagination, ActivityFeedResponse, ActivityLogResponse
from api.schemas.auth import UserResponse
from services import activity_service

router = APIRouter(prefix="/activity", tags=["Activity Feed"])


def _serialise_event(event) -> ActivityLogResponse:
    """Convert ActivityLog ORM instance into API response schema."""
    return ActivityLogResponse.model_validate(event.to_dict())


@router.get(
    "/",
    response_model=ActivityFeedResponse,
    summary="List recent activity events",
    description="Retrieve recent activity log entries with optional filtering by user, action type, resource, or time window.",
)
async def list_activity_feed(
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[UserResponse, Depends(get_current_user_with_db)],
    limit: int = Query(
        default=50,
        ge=1,
        le=200,
        description="Maximum number of activity events to return",
    ),
    offset: int = Query(
        default=0,
        ge=0,
        description="Number of activity events to skip before returning results",
    ),
    user_id: Optional[UUID] = Query(
        default=None,
        description="Filter to activity generated by a specific user",
    ),
    action_type: Optional[str] = Query(
        default=None,
        description="Filter by activity action type identifier",
    ),
    resource_type: Optional[str] = Query(
        default=None,
        description="Filter by affected resource/entity type",
    ),
    since: Optional[datetime] = Query(
        default=None,
        description="Return activity created on or after this timestamp",
    ),
) -> ActivityFeedResponse:
    """List recent activity log entries using the activity service."""
    events = await activity_service.list_recent(
        db=db,
        limit=limit,
        offset=offset,
        user_id=user_id,
        action_type=action_type,
        resource_type=resource_type,
        since=since,
    )

    pagination = ActivityFeedPagination(
        limit=limit,
        offset=offset,
        returned=len(events),
        user_id=user_id,
        action_type=action_type,
        resource_type=resource_type,
        since=since,
    )

    return ActivityFeedResponse(
        items=[_serialise_event(event) for event in events],
        pagination=pagination,
    )
