"""Initial migration with all models

Revision ID: 2c7f20ae9e24
Revises: a4284142d309
Create Date: 2025-12-11 14:23:33.138095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
import os

# Add backend to path to import GUID
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from models.base import GUID

# revision identifiers, used by Alembic.
revision: str = '2c7f20ae9e24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('config_key', sa.String(length=255), nullable=False, comment='Unique configuration key'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description for administrators'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the configuration is active'),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Configuration data in JSON format'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('escalation_policies',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable name for the policy'),
    sa.Column('min_agreement_ratio', sa.Float(), nullable=False, comment='Minimum agreement ratio for auto-pass (0.0 to 1.0)'),
    sa.Column('min_confidence', sa.Float(), nullable=False, comment='Minimum confidence score for auto-pass (0.0 to 1.0)'),
    sa.Column('auto_pass_threshold', sa.Float(), nullable=False, comment='Combined threshold for automatic pass'),
    sa.Column('escalate_threshold', sa.Float(), nullable=False, comment='Threshold below which to escalate to human review'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the policy is currently active'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional configuration settings'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_policies_is_active'), 'escalation_policies', ['is_active'], unique=False)
    op.create_table('judge_personas',
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Persona name'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='Base system prompt for the LLM judge'),
    sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of evaluation criteria'),
    sa.Column('strictness_level', sa.String(length=50), nullable=False, comment='Strictness level: strict, moderate, lenient'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of the persona and its use case'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the persona is active for use'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional configuration options'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_personas_is_active'), 'judge_personas', ['is_active'], unique=False)
    op.create_index(op.f('ix_judge_personas_strictness_level'), 'judge_personas', ['strictness_level'], unique=False)
    op.create_index(op.f('ix_judge_personas_tenant_id'), 'judge_personas', ['tenant_id'], unique=False)
    op.create_table('llm_judges',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable name for the judge'),
    sa.Column('provider', sa.String(length=100), nullable=False, comment='LLM provider (openai, anthropic, google, etc.)'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Specific model name (gpt-4, claude-3-opus, etc.)'),
    sa.Column('persona', sa.String(length=255), nullable=True, comment='Judge persona/style (strict, lenient, technical, etc.)'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='System prompt for the judge'),
    sa.Column('weight', sa.Float(), nullable=False, comment='Voting weight for weighted consensus'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the judge is currently active'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional configuration (temperature, max_tokens, etc.)'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_judges_is_active'), 'llm_judges', ['is_active'], unique=False)
    op.create_index(op.f('ix_llm_judges_provider'), 'llm_judges', ['provider'], unique=False)
    op.create_table('test_metrics',
    sa.Column('id', GUID(), nullable=False, comment='Primary identifier for the metric point'),
    sa.Column('metric_type', sa.String(length=100), nullable=False, comment='Metric name such as execution_time or pass_rate'),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='Numeric value observed for the metric'),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dimension key/value pairs (language, environment, etc.)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the metric was recorded'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Insert timestamp for the metric point'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address for authentication"),
    sa.Column('username', sa.String(length=100), nullable=False, comment="User's username for display and authentication"),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full legal name"),
    sa.Column('role', sa.String(length=50), nullable=True, comment="User's role for authorization (admin, user, etc)"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.Column('language_proficiencies', postgresql.ARRAY(sa.String(length=10)), nullable=True, comment='Array of language codes user is proficient in'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_log',
    sa.Column('id', GUID(), nullable=False, comment='Primary identifier for the activity event'),
    sa.Column('user_id', GUID(), nullable=False, comment='Reference to the user who performed the action'),
    sa.Column('action_type', sa.String(length=100), nullable=False, comment='Short descriptor for the type of action performed'),
    sa.Column('resource_type', sa.String(length=100), nullable=True, comment='Domain entity affected by the action, e.g. test_case'),
    sa.Column('resource_id', GUID(), nullable=True, comment='Identifier of the affected resource when applicable'),
    sa.Column('action_description', sa.Text(), nullable=True, comment='Human-readable description of the action for activity feeds'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured metadata payload describing the event'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP address associated with the action, if available'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the activity was recorded'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_action_type'), 'activity_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_log_resource_type'), 'activity_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_activity_log_user_id'), 'activity_log', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Domain entity type the comment is attached to (test_case, defect, validation)'),
    sa.Column('entity_id', GUID(), nullable=False, comment='Identifier of the entity the comment references'),
    sa.Column('parent_comment_id', GUID(), nullable=True, comment='Optional parent comment to support threaded replies'),
    sa.Column('author_id', GUID(), nullable=False, comment='Author of the comment referencing users table'),
    sa.Column('content', sa.Text(), nullable=False, comment='Comment body text (supports markdown)'),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Array of mentioned user identifiers and metadata'),
    sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Flag indicating whether the comment has been edited'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_type'), 'comments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_table('configuration_history',
    sa.Column('configuration_id', GUID(), nullable=False, comment='Configuration this history entry belongs to'),
    sa.Column('config_key', sa.String(length=255), nullable=True, comment='Configuration key at time of change'),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous configuration value'),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='New configuration value'),
    sa.Column('changed_by', GUID(), nullable=True, comment='User who made the change'),
    sa.Column('change_reason', sa.Text(), nullable=True, comment='Reason provided for the configuration change'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_history_changed_by'), 'configuration_history', ['changed_by'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Human-readable article title'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Optional grouping such as troubleshooting or best_practices'),
    sa.Column('content', sa.Text(), nullable=False, comment='Rich text or markdown body of the article'),
    sa.Column('content_format', sa.String(length=50), server_default=sa.text("'markdown'"), nullable=False, comment='Content format descriptor e.g. markdown or html'),
    sa.Column('author_id', GUID(), nullable=False, comment='Reference to the author in the users table'),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether the article is visible to readers'),
    sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Total number of recorded article views'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_author_id'), 'knowledge_base', ['author_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_table('scenario_scripts',
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Scenario script name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the scenario'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='Version string (e.g., 1.0.0)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the scenario is active'),
    sa.Column('script_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata (language, domain, tags, etc.)'),
    sa.Column('created_by', GUID(), nullable=True, comment='User who created this scenario'),
    sa.Column('owner_id', GUID(), nullable=True, comment='User who owns/is responsible for this scenario'),
    sa.Column('approval_status', sa.String(length=50), nullable=False, comment='Approval status: draft, pending_review, approved, rejected'),
    sa.Column('reviewed_by', GUID(), nullable=True, comment='User who reviewed this scenario'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when scenario was reviewed'),
    sa.Column('review_notes', sa.Text(), nullable=True, comment='Reviewer feedback or notes'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_scripts_approval_status'), 'scenario_scripts', ['approval_status'], unique=False)
    op.create_index(op.f('ix_scenario_scripts_created_by'), 'scenario_scripts', ['created_by'], unique=False)
    op.create_index(op.f('ix_scenario_scripts_is_active'), 'scenario_scripts', ['is_active'], unique=False)
    op.create_index(op.f('ix_scenario_scripts_owner_id'), 'scenario_scripts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_scenario_scripts_reviewed_by'), 'scenario_scripts', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_scenario_scripts_tenant_id'), 'scenario_scripts', ['tenant_id'], unique=False)
    op.create_table('test_suites',
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Test suite name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Test suite description'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Test suite category for organization'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether test suite is active'),
    sa.Column('created_by', GUID(), nullable=True, comment='User who created this test suite'),
    sa.Column('judge_persona_id', GUID(), nullable=True, comment='Judge persona to use for this test suite'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['judge_persona_id'], ['judge_personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suites_category'), 'test_suites', ['category'], unique=False)
    op.create_index(op.f('ix_test_suites_created_by'), 'test_suites', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_suites_is_active'), 'test_suites', ['is_active'], unique=False)
    op.create_index(op.f('ix_test_suites_judge_persona_id'), 'test_suites', ['judge_persona_id'], unique=False)
    op.create_index(op.f('ix_test_suites_name'), 'test_suites', ['name'], unique=False)
    op.create_index(op.f('ix_test_suites_tenant_id'), 'test_suites', ['tenant_id'], unique=False)
    op.create_table('validator_performance',
    sa.Column('validator_id', GUID(), nullable=False, comment='User (validator) whose performance is being tracked'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date for which performance metrics are recorded'),
    sa.Column('validations_completed', sa.Integer(), nullable=False, comment='Number of validations completed on this date'),
    sa.Column('average_time_seconds', sa.Numeric(precision=8, scale=2), nullable=True, comment='Average time spent per validation in seconds'),
    sa.Column('agreement_with_peers_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage agreement with peer validators (0.00-100.00)'),
    sa.Column('agreement_with_final_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage agreement with final consensus (0.00-100.00)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When this performance record was created'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_performance_date'), 'validator_performance', ['date'], unique=False)
    op.create_index(op.f('ix_validator_performance_validator_id'), 'validator_performance', ['validator_id'], unique=False)
    op.create_table('scenario_steps',
    sa.Column('script_id', GUID(), nullable=False, comment='Parent scenario script'),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='Order of this step in the scenario'),
    sa.Column('user_utterance', sa.Text(), nullable=False, comment='User input/utterance for this step'),
    sa.Column('expected_response', sa.Text(), nullable=False, comment='Primary expected system response'),
    sa.Column('alternate_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of acceptable alternative responses'),
    sa.Column('tolerances', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Validation tolerance settings'),
    sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional step-specific metadata'),
    sa.Column('follow_up_action', sa.String(length=100), nullable=True, comment='Follow-up action to trigger after step (await_confirmation, retry, etc.)'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['script_id'], ['scenario_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_steps_script_id'), 'scenario_steps', ['script_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('suite_id', GUID(), nullable=True, comment='Test suite this test case belongs to'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Test case name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Test case description'),
    sa.Column('test_type', sa.String(length=100), nullable=True, comment='Type of test: voice_command, multi_turn, edge_case'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Category: navigation, media, climate, etc.'),
    sa.Column('scenario_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='YAML/JSON scenario definition'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='Test case version'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether test case is active'),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True, comment='Array of tags for categorization'),
    sa.Column('created_by', GUID(), nullable=True, comment='User who created this test case'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_category'), 'test_cases', ['category'], unique=False)
    op.create_index(op.f('ix_test_cases_created_by'), 'test_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_cases_is_active'), 'test_cases', ['is_active'], unique=False)
    op.create_index(op.f('ix_test_cases_suite_id'), 'test_cases', ['suite_id'], unique=False)
    op.create_index(op.f('ix_test_cases_tenant_id'), 'test_cases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_cases_test_type'), 'test_cases', ['test_type'], unique=False)
    op.create_table('test_runs',
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('suite_id', GUID(), nullable=False, comment='Test suite being run'),
    sa.Column('created_by', GUID(), nullable=True, comment='User who initiated the test run'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Test run status (pending, running, completed, failed, cancelled)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When test run execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When test run execution completed'),
    sa.Column('total_tests', sa.Integer(), nullable=True, comment='Total number of tests in the run'),
    sa.Column('passed_tests', sa.Integer(), nullable=True, comment='Number of tests that passed'),
    sa.Column('failed_tests', sa.Integer(), nullable=True, comment='Number of tests that failed'),
    sa.Column('skipped_tests', sa.Integer(), nullable=True, comment='Number of tests that were skipped'),
    sa.Column('trigger_type', sa.String(length=50), nullable=True, comment='Type of trigger (manual, scheduled, api, webhook)'),
    sa.Column('trigger_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional trigger metadata including languages'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_created_by'), 'test_runs', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_suite_id'), 'test_runs', ['suite_id'], unique=False)
    op.create_index(op.f('ix_test_runs_tenant_id'), 'test_runs', ['tenant_id'], unique=False)
    op.create_table('defects',
    sa.Column('id', GUID(), nullable=False, comment='Primary identifier for the defect record'),
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('test_case_id', GUID(), nullable=True, comment='Associated test case that produced the defect'),
    sa.Column('test_execution_id', GUID(), nullable=True, comment='Test run in which the defect was detected'),
    sa.Column('severity', sa.String(length=50), nullable=False, comment='Severity classification (critical, high, medium, low)'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Defect category such as semantic, timing, or audio'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short summary describing the defect'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed narrative describing the defect'),
    sa.Column('language_code', sa.String(length=10), nullable=True, comment='Language code associated with the defect'),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the defect was identified'),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False, comment='Lifecycle status (open, in_progress, resolved)'),
    sa.Column('assigned_to', GUID(), nullable=True, comment='User currently assigned to resolve the defect'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the defect was resolved'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Insert timestamp for the defect record'),
    sa.Column('jira_issue_key', sa.String(length=100), nullable=True, comment='Associated Jira issue key (e.g., QA-123)'),
    sa.Column('jira_issue_url', sa.String(length=2048), nullable=True, comment='Link to the Jira issue for quick navigation'),
    sa.Column('jira_status', sa.String(length=100), nullable=True, comment='Last known Jira workflow status for the linked issue'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_assigned_to'), 'defects', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_defects_tenant_id'), 'defects', ['tenant_id'], unique=False)
    op.create_table('device_test_executions',
    sa.Column('test_run_id', GUID(), nullable=False, comment='Test run this execution belongs to'),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Device information (model, OS version, manufacturer, etc.)'),
    sa.Column('platform_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform-specific details (capabilities, features, etc.)'),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Test execution results and metrics'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_test_executions_test_run_id'), 'device_test_executions', ['test_run_id'], unique=False)
    op.create_table('edge_cases',
    sa.Column('id', GUID(), nullable=False, comment='Primary identifier for the edge case record'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Human-readable summary of the edge case'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed narrative describing the unexpected behaviour'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Category such as audio_quality, ambiguity, or context_loss'),
    sa.Column('severity', sa.String(length=50), nullable=True, comment='Impact level of the edge case (critical, high, medium, low)'),
    sa.Column('scenario_definition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='Structured definition detailing steps, utterances, expectations'),
    sa.Column('test_case_id', GUID(), nullable=True, comment='Linked regression test case that exhibits the edge case'),
    sa.Column('discovered_date', sa.Date(), nullable=True, comment='Date when the edge case was first reported'),
    sa.Column('discovered_by', GUID(), nullable=True, comment='User who reported or confirmed the edge case'),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False, comment='Lifecycle state: active, resolved, or wont_fix'),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text('ARRAY[]::text[]'), nullable=False, comment='Custom tags used for searching and grouping edge cases'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the edge case was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the edge case was last updated'),
    sa.ForeignKeyConstraint(['discovered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_cases_discovered_by'), 'edge_cases', ['discovered_by'], unique=False)
    op.create_table('expected_outcomes',
    sa.Column('outcome_code', sa.String(length=100), nullable=False, comment='Unique code identifying this expected outcome'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable name of the outcome'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the expected outcome'),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Expected entities to be extracted (JSON structure)'),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Validation rules for verifying outcome (JSON structure)'),
    sa.Column('language_variations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Language-specific variations of expected outcomes (JSON structure)'),
    sa.Column('scenario_step_id', GUID(), nullable=True, comment='Reference to the scenario step this outcome applies to'),
    sa.Column('acceptable_alternates', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of acceptable alternate responses (JSON array)'),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False, comment='Whether confirmation is required before success'),
    sa.Column('confirmation_prompt', sa.Text(), nullable=True, comment='The expected confirmation prompt'),
    sa.Column('allow_partial_success', sa.Boolean(), nullable=False, comment='Whether partial success is acceptable'),
    sa.Column('tolerance_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Tolerance settings for validation (semantic similarity, entity matching)'),
    sa.Column('tolerance_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete tolerance configuration for this outcome'),
    sa.Column('required_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of entities that must be present in response'),
    sa.Column('forbidden_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of phrases that must not appear in response'),
    sa.Column('tone_requirement', sa.String(length=100), nullable=True, comment='Required tone for response (polite, professional, etc.)'),
    sa.Column('max_response_length', sa.Integer(), nullable=True, comment='Maximum allowed response length in characters'),
    sa.Column('next_step_on_success', GUID(), nullable=True, comment='Next step ID on successful validation'),
    sa.Column('next_step_on_failure', GUID(), nullable=True, comment='Next step ID on failed validation'),
    sa.Column('recovery_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Recovery path configuration for failed validations'),
    sa.Column('scenario_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional scenario-specific metadata'),
    sa.Column('dynamic_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dynamic context for resolving references (e.g., search results)'),
    sa.Column('expected_command_kind', sa.String(length=100), nullable=True, comment='Expected Houndify CommandKind (WeatherCommand, MusicCommand, NoResultCommand, etc.)'),
    sa.Column('expected_intent', sa.String(length=100), nullable=True, comment='Expected user intent classification within the command domain'),
    sa.Column('expected_asr_confidence_min', sa.Float(), nullable=True, comment='Minimum required ASR confidence score from Houndify (0.0 - 1.0)'),
    sa.Column('expected_response_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Expected content patterns in SpokenResponse/WrittenResponse from Houndify'),
    sa.Column('expected_native_data_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Expected structure and value constraints for Houndify NativeData field'),
    sa.Column('conversation_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Conversation state requirements for multi-turn interactions'),
    sa.Column('enforce_command_intent_consistency', sa.Boolean(), nullable=False, comment='Validate that extracted intent is consistent with CommandKind'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['scenario_step_id'], ['scenario_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_outcomes_expected_command_kind'), 'expected_outcomes', ['expected_command_kind'], unique=False)
    op.create_index(op.f('ix_expected_outcomes_expected_intent'), 'expected_outcomes', ['expected_intent'], unique=False)
    op.create_index(op.f('ix_expected_outcomes_outcome_code'), 'expected_outcomes', ['outcome_code'], unique=True)
    op.create_index(op.f('ix_expected_outcomes_scenario_step_id'), 'expected_outcomes', ['scenario_step_id'], unique=False)
    op.create_table('multi_turn_executions',
    sa.Column('test_run_id', GUID(), nullable=False, comment='Test run this execution belongs to'),
    sa.Column('script_id', GUID(), nullable=False, comment='Scenario script being executed'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Houndify user_id for conversation tracking'),
    sa.Column('conversation_state_id', sa.String(length=255), nullable=True, comment='ConversationStateId from Houndify'),
    sa.Column('current_step_order', sa.Integer(), nullable=False, comment='Current step being executed (0 = not started)'),
    sa.Column('total_steps', sa.Integer(), nullable=False, comment='Total number of steps in scenario'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Execution status: pending, in_progress, completed, failed, cancelled'),
    sa.Column('conversation_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full conversation state from Houndify (JSONB)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When execution completed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if execution failed'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['script_id'], ['scenario_scripts.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_turn_executions_conversation_state_id'), 'multi_turn_executions', ['conversation_state_id'], unique=False)
    op.create_index(op.f('ix_multi_turn_executions_script_id'), 'multi_turn_executions', ['script_id'], unique=False)
    op.create_index(op.f('ix_multi_turn_executions_status'), 'multi_turn_executions', ['status'], unique=False)
    op.create_index(op.f('ix_multi_turn_executions_test_run_id'), 'multi_turn_executions', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_multi_turn_executions_user_id'), 'multi_turn_executions', ['user_id'], unique=False)
    op.create_table('test_case_languages',
    sa.Column('test_case_id', GUID(), nullable=False, comment='Test case this language variation belongs to'),
    sa.Column('language_code', sa.String(length=10), nullable=False, comment='Language code (e.g., en, es, fr)'),
    sa.Column('input_text', sa.Text(), nullable=True, comment='Primary input text for this language'),
    sa.Column('input_variations', postgresql.ARRAY(sa.Text()), nullable=True, comment='Multiple phrasings for the same input'),
    sa.Column('translation_status', sa.String(length=50), nullable=True, comment='Translation status (draft, reviewed, approved)'),
    sa.Column('reviewed_by', GUID(), nullable=True, comment='User who reviewed this translation'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='When this translation was reviewed'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_languages_language_code'), 'test_case_languages', ['language_code'], unique=False)
    op.create_index(op.f('ix_test_case_languages_test_case_id'), 'test_case_languages', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_case_languages_translation_status'), 'test_case_languages', ['translation_status'], unique=False)
    op.create_table('test_case_versions',
    sa.Column('id', GUID(), nullable=False, comment='Primary identifier for the version snapshot'),
    sa.Column('test_case_id', GUID(), nullable=False, comment='Test case the snapshot belongs to'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Sequential version number scoped to the test case'),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Serialized representation of the test case after update'),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Computed diff compared to the previous version snapshot'),
    sa.Column('change_summary', sa.String(length=255), nullable=True, comment='Optional free-text summary of the change'),
    sa.Column('created_by', GUID(), nullable=True, comment='User responsible for the update that generated this version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the snapshot was recorded'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_versions_created_by'), 'test_case_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_case_versions_test_case_id'), 'test_case_versions', ['test_case_id'], unique=False)
    op.create_table('test_execution_queue',
    sa.Column('test_run_id', GUID(), nullable=False, comment='Test run to be executed'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Execution priority (higher number = higher priority)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Queue status (queued, processing, completed, failed)'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_execution_queue_priority'), 'test_execution_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_test_execution_queue_status'), 'test_execution_queue', ['status'], unique=False)
    op.create_index(op.f('ix_test_execution_queue_test_run_id'), 'test_execution_queue', ['test_run_id'], unique=False)
    op.create_table('translation_tasks',
    sa.Column('id', GUID(), nullable=False, comment='Primary key identifier for the translation task'),
    sa.Column('test_case_id', GUID(), nullable=False, comment='Associated test case requiring translation'),
    sa.Column('source_language', sa.String(length=10), nullable=False, comment='Language code of the original content'),
    sa.Column('target_language', sa.String(length=10), nullable=False, comment='Language code of the translation output'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Task status: pending, in_progress, review, completed'),
    sa.Column('assigned_to', GUID(), nullable=True, comment='User assigned to perform the translation'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the translation was completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the translation task was created'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_executions',
    sa.Column('multi_turn_execution_id', GUID(), nullable=False, comment='Parent multi-turn execution'),
    sa.Column('step_id', GUID(), nullable=False, comment='Scenario step being executed'),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='Order of this step in the scenario'),
    sa.Column('user_utterance', sa.Text(), nullable=False, comment='What the user said'),
    sa.Column('audio_data_url', sa.String(length=500), nullable=True, comment='S3 URL to audio file'),
    sa.Column('request_id', sa.String(length=255), nullable=False, comment='Houndify request ID'),
    sa.Column('ai_response', sa.Text(), nullable=True, comment="AI's spoken response"),
    sa.Column('transcription', sa.Text(), nullable=True, comment='Transcription of user utterance'),
    sa.Column('command_kind', sa.String(length=100), nullable=True, comment='Houndify CommandKind'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Recognition confidence score (0.0 to 1.0)'),
    sa.Column('conversation_state_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Conversation state before this step (JSONB)'),
    sa.Column('conversation_state_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Conversation state after this step (JSONB)'),
    sa.Column('validation_passed', sa.Boolean(), nullable=True, comment='Whether validation passed for this step'),
    sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detailed validation results (JSONB)'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='API response time in milliseconds'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False, comment='When step was executed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if step failed'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['multi_turn_execution_id'], ['multi_turn_executions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['scenario_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_executions_multi_turn_execution_id'), 'step_executions', ['multi_turn_execution_id'], unique=False)
    op.create_index(op.f('ix_step_executions_request_id'), 'step_executions', ['request_id'], unique=False)
    op.create_index(op.f('ix_step_executions_step_id'), 'step_executions', ['step_id'], unique=False)
    op.create_table('voice_test_executions',
    sa.Column('test_run_id', GUID(), nullable=False, comment='Test run this execution belongs to'),
    sa.Column('test_case_id', GUID(), nullable=True, comment='Test case executed'),
    sa.Column('expected_outcome_id', GUID(), nullable=True, comment='Expected outcome for this execution'),
    sa.Column('language_code', sa.String(length=10), nullable=True, comment='Language code used for execution'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Execution status: pending/running/completed/failed/skipped'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when execution completed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Optional error message if execution failed'),
    sa.Column('audio_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Audio parameters (sample rate, format, etc.)'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Test execution context (environment, device info, etc.)'),
    sa.Column('response_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extracted entities from voice response'),
    sa.Column('audio_duration', sa.Float(), nullable=True, comment='Duration of audio in seconds'),
    sa.Column('processing_time', sa.Float(), nullable=True, comment='Time taken to process audio in seconds'),
    sa.Column('rtf', sa.Float(), nullable=True, comment='Real-Time Factor = processing_time / audio_duration'),
    sa.Column('first_byte_latency', sa.Float(), nullable=True, comment='Time to first transcription token in seconds'),
    sa.Column('final_result_latency', sa.Float(), nullable=True, comment='Time to complete transcription in seconds'),
    sa.Column('network_latency', sa.Float(), nullable=True, comment='Network round-trip time in seconds'),
    sa.Column('processing_mode', sa.String(length=50), nullable=True, comment="Processing mode: 'streaming' or 'batch'"),
    sa.Column('input_audio_url', sa.Text(), nullable=True, comment='S3/MinIO URL for input audio (TTS generated)'),
    sa.Column('response_audio_url', sa.Text(), nullable=True, comment='S3/MinIO URL for response audio (if captured)'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['expected_outcome_id'], ['expected_outcomes.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_test_executions_expected_outcome_id'), 'voice_test_executions', ['expected_outcome_id'], unique=False)
    op.create_index(op.f('ix_voice_test_executions_test_case_id'), 'voice_test_executions', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_voice_test_executions_test_run_id'), 'voice_test_executions', ['test_run_id'], unique=False)
    op.create_index('ix_voice_test_executions_test_run_id_status', 'voice_test_executions', ['test_run_id', 'status'], unique=False)
    op.create_table('validation_results',
    sa.Column('tenant_id', GUID(), nullable=True, comment='Tenant identifier for multi-tenant scoping'),
    sa.Column('test_run_id', GUID(), nullable=False, comment='Test run this validation belongs to'),
    sa.Column('accuracy_score', sa.Float(), nullable=True, comment='Overall accuracy score (0.0 to 1.0)'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Confidence score of the validation (0.0 to 1.0)'),
    sa.Column('semantic_similarity_score', sa.Float(), nullable=True, comment='Semantic similarity between expected and actual (0.0 to 1.0)'),
    sa.Column('intent_match_score', sa.Float(), nullable=True, comment='Intent matching score (0.0 to 1.0)'),
    sa.Column('entity_match_score', sa.Float(), nullable=True, comment='Entity extraction matching score (0.0 to 1.0)'),
    sa.Column('wer_score', sa.Float(), nullable=True, comment='Word Error Rate score for ASR quality (0.0 = perfect, higher = more errors)'),
    sa.Column('cer_score', sa.Float(), nullable=True, comment='Character Error Rate score for ASR quality (0.0 = perfect, higher = more errors)'),
    sa.Column('ser_score', sa.Float(), nullable=True, comment='Sentence Error Rate score - percentage of utterances with any error (0.0 = all perfect, 1.0 = all have errors)'),
    sa.Column('command_kind_match_score', sa.Float(), nullable=True, comment='CommandKind match score - 1.0 if matches expected CommandKind, 0.0 otherwise'),
    sa.Column('asr_confidence_score', sa.Float(), nullable=True, comment='ASR confidence score from Houndify (0.0 to 1.0)'),
    sa.Column('command_intent_consistency_score', sa.Float(), nullable=True, comment='Command-Intent consistency score - 1.0 if intent matches CommandKind, 0.0 otherwise'),
    sa.Column('voice_test_execution_id', GUID(), nullable=True, comment='Voice test execution validated in this result'),
    sa.Column('expected_outcome_id', GUID(), nullable=True, comment='Expected outcome reference for this validation'),
    sa.Column('review_status', sa.String(length=32), nullable=True, comment='auto_pass/needs_review/auto_fail status from validation'),
    sa.Column('ensemble_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ensemble judge result with consensus and individual decisions'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['expected_outcome_id'], ['expected_outcomes.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.ForeignKeyConstraint(['voice_test_execution_id'], ['voice_test_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_expected_outcome_id'), 'validation_results', ['expected_outcome_id'], unique=False)
    op.create_index(op.f('ix_validation_results_tenant_id'), 'validation_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_validation_results_test_run_id'), 'validation_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_validation_results_voice_test_execution_id'), 'validation_results', ['voice_test_execution_id'], unique=False)
    op.create_table('human_validations',
    sa.Column('validation_result_id', GUID(), nullable=False, comment='Reference to the validation result being reviewed'),
    sa.Column('validator_id', GUID(), nullable=False, comment='User performing the validation'),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True, comment='When the validator claimed this validation task'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='When the validation decision was submitted'),
    sa.Column('validation_decision', sa.String(length=50), nullable=True, comment="Validation decision: 'pass', 'fail', or 'edge_case'"),
    sa.Column('feedback', sa.Text(), nullable=True, comment='Optional feedback and notes from the validator'),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True, comment='Time spent on validation in seconds'),
    sa.Column('is_second_opinion', sa.Boolean(), nullable=False, comment='Whether this is a second validation for quality assurance'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_validations_validation_decision'), 'human_validations', ['validation_decision'], unique=False)
    op.create_index(op.f('ix_human_validations_validation_result_id'), 'human_validations', ['validation_result_id'], unique=False)
    op.create_index(op.f('ix_human_validations_validator_id'), 'human_validations', ['validator_id'], unique=False)
    op.create_table('judge_decisions',
    sa.Column('validation_result_id', GUID(), nullable=False, comment='Reference to the validation result'),
    sa.Column('judge_id', GUID(), nullable=False, comment='Reference to the LLM judge'),
    sa.Column('decision', sa.String(length=50), nullable=False, comment='Decision: pass or fail'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score (0.0 to 1.0)'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='Explanation for the decision'),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full LLM response for debugging'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Response time in milliseconds'),
    sa.Column('persona_id', GUID(), nullable=True, comment='Judge persona used for this decision'),
    sa.Column('persona_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Persona metadata snapshot for audit trail'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['judge_id'], ['llm_judges.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['judge_personas.id'], ),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_decisions_decision'), 'judge_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_judge_decisions_judge_id'), 'judge_decisions', ['judge_id'], unique=False)
    op.create_index(op.f('ix_judge_decisions_persona_id'), 'judge_decisions', ['persona_id'], unique=False)
    op.create_index(op.f('ix_judge_decisions_validation_result_id'), 'judge_decisions', ['validation_result_id'], unique=False)
    op.create_table('validation_queue',
    sa.Column('validation_result_id', GUID(), nullable=False, comment='Reference to the validation result to be reviewed'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority level for queue ordering (1=highest, 10=lowest, default=5)'),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='AI confidence score (0.00-100.00) indicating uncertainty'),
    sa.Column('language_code', sa.String(length=10), nullable=True, comment='Language code for matching to validators with language proficiency'),
    sa.Column('claimed_by', GUID(), nullable=True, comment='User who claimed this validation task'),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True, comment='When the validation task was claimed'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="Queue status: 'pending', 'claimed', 'completed'"),
    sa.Column('requires_native_speaker', sa.Boolean(), nullable=False, comment='Whether this validation requires a native speaker'),
    sa.Column('id', GUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_queue_claimed_by'), 'validation_queue', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_validation_queue_language_code'), 'validation_queue', ['language_code'], unique=False)
    op.create_index(op.f('ix_validation_queue_priority'), 'validation_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_validation_queue_status'), 'validation_queue', ['status'], unique=False)
    op.create_index(op.f('ix_validation_queue_validation_result_id'), 'validation_queue', ['validation_result_id'], unique=False)
    op.create_index('ix_validation_queue_validation_result_id_status', 'validation_queue', ['validation_result_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_queue_validation_result_id_status', table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_validation_result_id'), table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_status'), table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_priority'), table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_language_code'), table_name='validation_queue')
    op.drop_index(op.f('ix_validation_queue_claimed_by'), table_name='validation_queue')
    op.drop_table('validation_queue')
    op.drop_index(op.f('ix_judge_decisions_validation_result_id'), table_name='judge_decisions')
    op.drop_index(op.f('ix_judge_decisions_persona_id'), table_name='judge_decisions')
    op.drop_index(op.f('ix_judge_decisions_judge_id'), table_name='judge_decisions')
    op.drop_index(op.f('ix_judge_decisions_decision'), table_name='judge_decisions')
    op.drop_table('judge_decisions')
    op.drop_index(op.f('ix_human_validations_validator_id'), table_name='human_validations')
    op.drop_index(op.f('ix_human_validations_validation_result_id'), table_name='human_validations')
    op.drop_index(op.f('ix_human_validations_validation_decision'), table_name='human_validations')
    op.drop_table('human_validations')
    op.drop_index(op.f('ix_validation_results_voice_test_execution_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_test_run_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_tenant_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_expected_outcome_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index('ix_voice_test_executions_test_run_id_status', table_name='voice_test_executions')
    op.drop_index(op.f('ix_voice_test_executions_test_run_id'), table_name='voice_test_executions')
    op.drop_index(op.f('ix_voice_test_executions_test_case_id'), table_name='voice_test_executions')
    op.drop_index(op.f('ix_voice_test_executions_expected_outcome_id'), table_name='voice_test_executions')
    op.drop_table('voice_test_executions')
    op.drop_index(op.f('ix_step_executions_step_id'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_request_id'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_multi_turn_execution_id'), table_name='step_executions')
    op.drop_table('step_executions')
    op.drop_table('translation_tasks')
    op.drop_index(op.f('ix_test_execution_queue_test_run_id'), table_name='test_execution_queue')
    op.drop_index(op.f('ix_test_execution_queue_status'), table_name='test_execution_queue')
    op.drop_index(op.f('ix_test_execution_queue_priority'), table_name='test_execution_queue')
    op.drop_table('test_execution_queue')
    op.drop_index(op.f('ix_test_case_versions_test_case_id'), table_name='test_case_versions')
    op.drop_index(op.f('ix_test_case_versions_created_by'), table_name='test_case_versions')
    op.drop_table('test_case_versions')
    op.drop_index(op.f('ix_test_case_languages_translation_status'), table_name='test_case_languages')
    op.drop_index(op.f('ix_test_case_languages_test_case_id'), table_name='test_case_languages')
    op.drop_index(op.f('ix_test_case_languages_language_code'), table_name='test_case_languages')
    op.drop_table('test_case_languages')
    op.drop_index(op.f('ix_multi_turn_executions_user_id'), table_name='multi_turn_executions')
    op.drop_index(op.f('ix_multi_turn_executions_test_run_id'), table_name='multi_turn_executions')
    op.drop_index(op.f('ix_multi_turn_executions_status'), table_name='multi_turn_executions')
    op.drop_index(op.f('ix_multi_turn_executions_script_id'), table_name='multi_turn_executions')
    op.drop_index(op.f('ix_multi_turn_executions_conversation_state_id'), table_name='multi_turn_executions')
    op.drop_table('multi_turn_executions')
    op.drop_index(op.f('ix_expected_outcomes_scenario_step_id'), table_name='expected_outcomes')
    op.drop_index(op.f('ix_expected_outcomes_outcome_code'), table_name='expected_outcomes')
    op.drop_index(op.f('ix_expected_outcomes_expected_intent'), table_name='expected_outcomes')
    op.drop_index(op.f('ix_expected_outcomes_expected_command_kind'), table_name='expected_outcomes')
    op.drop_table('expected_outcomes')
    op.drop_index(op.f('ix_edge_cases_discovered_by'), table_name='edge_cases')
    op.drop_table('edge_cases')
    op.drop_index(op.f('ix_device_test_executions_test_run_id'), table_name='device_test_executions')
    op.drop_table('device_test_executions')
    op.drop_index(op.f('ix_defects_tenant_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_assigned_to'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_test_runs_tenant_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_suite_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_created_by'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_cases_test_type'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_tenant_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_suite_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_is_active'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_created_by'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_category'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_scenario_steps_script_id'), table_name='scenario_steps')
    op.drop_table('scenario_steps')
    op.drop_index(op.f('ix_validator_performance_validator_id'), table_name='validator_performance')
    op.drop_index(op.f('ix_validator_performance_date'), table_name='validator_performance')
    op.drop_table('validator_performance')
    op.drop_index(op.f('ix_test_suites_tenant_id'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_name'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_judge_persona_id'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_is_active'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_created_by'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_category'), table_name='test_suites')
    op.drop_table('test_suites')
    op.drop_index(op.f('ix_scenario_scripts_tenant_id'), table_name='scenario_scripts')
    op.drop_index(op.f('ix_scenario_scripts_reviewed_by'), table_name='scenario_scripts')
    op.drop_index(op.f('ix_scenario_scripts_owner_id'), table_name='scenario_scripts')
    op.drop_index(op.f('ix_scenario_scripts_is_active'), table_name='scenario_scripts')
    op.drop_index(op.f('ix_scenario_scripts_created_by'), table_name='scenario_scripts')
    op.drop_index(op.f('ix_scenario_scripts_approval_status'), table_name='scenario_scripts')
    op.drop_table('scenario_scripts')
    op.drop_index(op.f('ix_knowledge_base_category'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_author_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_configuration_history_changed_by'), table_name='configuration_history')
    op.drop_table('configuration_history')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_activity_log_user_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_resource_type'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_action_type'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('test_metrics')
    op.drop_index(op.f('ix_llm_judges_provider'), table_name='llm_judges')
    op.drop_index(op.f('ix_llm_judges_is_active'), table_name='llm_judges')
    op.drop_table('llm_judges')
    op.drop_index(op.f('ix_judge_personas_tenant_id'), table_name='judge_personas')
    op.drop_index(op.f('ix_judge_personas_strictness_level'), table_name='judge_personas')
    op.drop_index(op.f('ix_judge_personas_is_active'), table_name='judge_personas')
    op.drop_table('judge_personas')
    op.drop_index(op.f('ix_escalation_policies_is_active'), table_name='escalation_policies')
    op.drop_table('escalation_policies')
    op.drop_table('configurations')
    # ### end Alembic commands ###
