"""
Voice AI Testing Framework - API Response Models
Standard response structures for API endpoints
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


def to_camel(string: str) -> str:
    """Convert snake_case to camelCase"""
    components = string.split('_')
    return components[0] + ''.join(x.title() for x in components[1:])


class CamelCaseModel(BaseModel):
    """Base model that converts snake_case fields to camelCase in JSON"""
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        from_attributes=True,
    )


# ============================================================================
# Success Response
# ============================================================================

class SuccessResponse(BaseModel):
    """
    Standard success response for API endpoints

    Used to return successful operation results with a consistent structure.
    The success field is always True to indicate successful completion.

    Attributes:
        success: Boolean flag indicating success (always True)
        data: The response data (can be any type - dict, list, string, etc.)

    Example:
        ```python
        from fastapi import APIRouter
        from api.schemas.responses import SuccessResponse

        router = APIRouter()

        @router.get("/users/{user_id}", response_model=SuccessResponse)
        async def get_user(user_id: int):
            user_data = {"id": user_id, "name": "John Doe"}
            return SuccessResponse(data=user_data)
        ```

        Response:
        ```json
        {
            "success": true,
            "data": {
                "id": 123,
                "name": "John Doe"
            }
        }
        ```
    """

    success: bool = Field(
        default=True,
        description="Success flag (always True for successful responses)"
    )
    data: Any = Field(
        ...,
        description="Response data (can be any type)"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "success": True,
                    "data": {
                        "id": 123,
                        "name": "Example User",
                        "email": "user@example.com"
                    }
                }
            ]
        }
    }


# ============================================================================
# Error Response
# ============================================================================

class ErrorResponse(BaseModel):
    """
    Standard error response for API endpoints

    Used to return error information with a consistent structure across
    all API endpoints. Includes request ID for tracking and debugging.

    Attributes:
        success: Boolean flag indicating failure (always False)
        error: Dictionary containing error details (code, message, etc.)
        request_id: Unique request identifier for tracking

    Example:
        ```python
        from fastapi import APIRouter, HTTPException
        from api.schemas.responses import ErrorResponse
        from api.logging_config import get_request_id

        router = APIRouter()

        @router.get("/users/{user_id}")
        async def get_user(user_id: int):
            if user_id not in database:
                # Error responses are typically handled by exception handlers
                raise HTTPException(status_code=404, detail="User not found")
        ```

        Error response (generated by exception handler):
        ```json
        {
            "success": false,
            "error": {
                "code": "NOT_FOUND",
                "message": "User not found"
            },
            "request_id": "req-abc-123"
        }
        ```
    """

    success: bool = Field(
        default=False,
        description="Success flag (always False for error responses)"
    )
    error: Dict[str, Any] = Field(
        ...,
        description="Error details including code, message, and additional context"
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Unique request identifier for tracking and debugging"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "success": False,
                    "error": {
                        "code": "VALIDATION_ERROR",
                        "message": "Invalid input data",
                        "details": {
                            "field": "email",
                            "issue": "invalid format"
                        }
                    },
                    "request_id": "req-xyz-789"
                }
            ]
        }
    }


# ============================================================================
# Paginated Response
# ============================================================================

class PaginatedResponse(BaseModel):
    """
    Standard paginated response for list endpoints

    Used to return paginated lists with metadata about total items,
    current page, and navigation information.

    Attributes:
        data: List of items for the current page
        pagination: Dictionary containing pagination metadata

    Pagination metadata typically includes:
        - page: Current page number (1-indexed)
        - per_page: Number of items per page
        - total: Total number of items across all pages
        - pages: Total number of pages
        - has_next: Whether there is a next page
        - has_prev: Whether there is a previous page

    Example:
        ```python
        from fastapi import APIRouter, Query
        from api.schemas.responses import PaginatedResponse

        router = APIRouter()

        @router.get("/users", response_model=PaginatedResponse)
        async def list_users(
            page: int = Query(1, ge=1),
            per_page: int = Query(10, ge=1, le=100)
        ):
            # Fetch paginated data from database
            users = get_users_page(page, per_page)
            total = get_total_users()

            return PaginatedResponse(
                data=users,
                pagination={
                    "page": page,
                    "per_page": per_page,
                    "total": total,
                    "pages": (total + per_page - 1) // per_page,
                    "has_next": page * per_page < total,
                    "has_prev": page > 1
                }
            )
        ```

        Response:
        ```json
        {
            "data": [
                {"id": 1, "name": "User 1"},
                {"id": 2, "name": "User 2"}
            ],
            "pagination": {
                "page": 1,
                "per_page": 10,
                "total": 25,
                "pages": 3,
                "has_next": true,
                "has_prev": false
            }
        }
        ```
    """

    data: List[Any] = Field(
        ...,
        description="List of items for the current page"
    )
    pagination: Dict[str, Any] = Field(
        ...,
        description="Pagination metadata (page, per_page, total, etc.)"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "data": [
                        {"id": 1, "name": "Item 1"},
                        {"id": 2, "name": "Item 2"}
                    ],
                    "pagination": {
                        "page": 1,
                        "per_page": 10,
                        "total": 25,
                        "pages": 3,
                        "has_next": True,
                        "has_prev": False
                    }
                }
            ]
        }
    }


# ============================================================================
# Export public API
# ============================================================================

__all__ = [
    'CamelCaseModel',
    'SuccessResponse',
    'ErrorResponse',
    'PaginatedResponse',
]
